baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Catholic Study Podcast"
theme = "castanet"

paginate = "9"

googleAnalytics = "UA-124193081-1"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

# [[Menu.Main]]
#     name = "Contact"
#     identifier = "contact"
#     url = "contact"

# [[Menu.Main]]
#     name = "Hosts"
#     identifier = "hosts"
#     url = "host"

# [[Menu.Main]]
#     name = "Guests"
#     identifier = "guests"
#     url = "guest"

# [[Menu.Main]]
#     name = "Resources"
#     identifier = "resources"
#     url = "#!"

# [[Menu.Main]]
#     name = "Books"
#     identifier = "books"
#     url = "books"
#     parent = "resources"
# [[Menu.Main]]
#     name = "Podcasts"
#     identifier = "podcasts"
#     url = "books"
#     parent = "resources"

[params]
site_theme = "grey"
custom_css = [ "css/override.css" ]
site_layout = "row"
enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/kevin.jpg"
# itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
# android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
# google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Study sacred scripture with a focus on historical context and interpretation. What did the scriptures mean to those to whom it was written? That's the key to knowing what it means to us today!"
media_prefix = "https://media.catholicstudypodcast.com/episodes/"
  [params.feed]
  # itunes rss details: https://help.apple.com/itc/podcasts_connect/#/itcb54353390
    feed_base_url = "https://www.catholicstudypodcast.com/"
    itunes_type = "episodic" # episodic or serial
    itunes_subtitle = "Historical, Literal, Catholic." #no markdown or HTML
    itunes_author = "Kevin Hammer" #no markdown or HTML
    itunes_summary = "Study sacred scripture with a focus on historical context and interpretation. What did the scriptures mean to those to whom it was written? That's the key to knowing what it means to us today!" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Kevin Hammer"
    itunes_owner_email = "galactichammer@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.catholicstudypodcast.com/apple-touch-icon.png" #fqdn to the image art for your podcast
    itunes_top_category = "Religion & Spirituality"
    itunes_first_sub_category = "Christianity"
    # itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.social]
    # github = "arresteddevops"
    # gitlab = "mattstratton"
    # facebook = "Arresteddevops"
    # facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    # twitter = "arresteddevops"
    # twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    # googleplus = "ArrestedDevOps"
    # pinterest = "nozzleio"
    # instagram = "nozzleio"
    # youtube = "arresteddevops"
    # linkedin = "mattstratton"

  [params.authors]
    [params.authors.Kevin]
      name	= "Kevin Hammer"
      thumbnail = "img/kevin.jpg"
      bio = "Kevin Hammer is long time Bible teacher who converted to the Catholic faith in 2011."
      [params.authors.Kevin.social]
        # github = "mattstratton"
        # facebook = "matt.stratton"
        # twitter = "mattstratton"
        # linkedin = "mattstratton"
        # homepage = "https://www.mattstratton.io"
        # pinterest = "mattstratton"
        # instagram = "instagram"
        # youtube = "mattstratton"
#     [params.authors.Trevor]
# 			name = "Trevor Hess"
# 			thumbnail = "https://www.arresteddevops.com/img/trevor.png"
# 			bio = ""
# 				[params.authors.Trevor.social]
# 					twitter = "trevorghess"
#     [params.authors.Bridget]
#       name = "Bridget Kromhout"
#       thumbnail = "https://www.arresteddevops.com/img/Bridget.png"
#       bio = ""
#       [params.authors.Bridget.social]
#         twitter = "bridgetkromhout"

#     [params.links]
#       [params.links.ado]
#         name = "Arrested DevOps"
#         url = "https://www.arresteddevops.com"
#       [params.links.ffs]
#         name = "Food Fight Show"
#         url = "https://foodfightshow.org"
#       [params.links.sdt]
#         name = "Software Defined Talk"
#         url = "https://cote.io/podcasts/sdt/"